services:
  - type: web
    name: portfolio
    env: static
    buildCommand: npm install && npm run generate
    staticPublishPath: .output/public
    envVars:
      - key: NODE_VERSION
        value: 18
